import { Navbar } from '@/components/Navbar'
import '../styles/global.sass'
import { Header } from '@/components/Header'
import { Providers } from './providers'
import Children from '@/components/Children'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="dark text-foreground bg-background">
            <body>
                <Providers>
                    <Header />
                    <div className="app">
                        <Navbar />
                        <Children>{children}</Children>
                    </div>
                </Providers>
            </body>
        </html>
    )
}
