import { Navbar } from '@/components/Navbar'
import '../styles/global.sass'
import { Header } from '@/components/Header'
import { AuthProvider } from '@/components/AuthProvider'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <Header />
                    <div className="app">
                        <Navbar />
                        <div className="page">{children}</div>
                    </div>
                </AuthProvider>
            </body>
        </html>
    )
}
